# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='schoolpage'),
        ),
    ]
