# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_No',
            fields=[
                ('day_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['day_name'],
                'verbose_name': 'Day #',
                'verbose_name_plural': "Day #'s",
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Kalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('day_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.Day_No')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='Kalendar_Setup',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Calendar Setup Name')),
                ('first_day_class', models.DateField()),
                ('days_in_cycle', models.PositiveSmallIntegerField(verbose_name='Days in Cycle')),
            ],
            options={
                'verbose_name': 'Calendar Setup',
                'verbose_name_plural': 'Calendar Setup',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kalendar.Kalendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='klass',
            field=models.ManyToManyField(blank=True, to='classlists.Klass'),
        ),
    ]
