# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlists', '0001_initial'),
        ('kalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=12, verbose_name='Activity')),
                ('org', models.BooleanField(default=True, verbose_name='Original')),
                ('del_date', models.DateField(blank=True)),
                ('day_no', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kalendar.Day_No')),
            ],
            options={
                'verbose_name': 'Period Activity',
                'verbose_name_plural': 'Period Activities',
            },
        ),
        migrations.CreateModel(
            name='Period_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Periods include lunch, recess, before and after school', verbose_name='Period #')),
                ('name', models.CharField(blank=True, max_length=14, verbose_name='Period Name')),
                ('start_time', models.CharField(blank=True, max_length=5)),
                ('end_time', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'Period Details',
                'verbose_name_plural': 'Period Details',
            },
        ),
        migrations.CreateModel(
            name='Schedule_Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Schedule Name')),
                ('periods_in_day', models.PositiveSmallIntegerField(help_text='Count before, after, lunch and recess as periods', verbose_name='Periods in a Day')),
            ],
            options={
                'verbose_name': 'Schedule Setup',
                'verbose_name_plural': 'Schedule Setup',
            },
        ),
        migrations.AddField(
            model_name='period_details',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule_Setup'),
        ),
        migrations.AddField(
            model_name='period_activity',
            name='details',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Period_Details'),
        ),
        migrations.AddField(
            model_name='period_activity',
            name='klass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass', verbose_name='Class'),
        ),
    ]
