# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlists', '0002_auto_20160805_2208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_on', models.DateField()),
                ('subject', models.CharField(choices=[('Language', 'Language'), ('Math', 'Math'), ('Science', 'Science'), ('French', 'French'), ('Visual Art', 'Visual Art'), ('Phys Ed.', 'Phys Ed.'), ('Geography', 'Geography'), ('History', 'History'), ('Drama', 'Drama'), ('Dance', 'Dance'), ('Media', 'Media'), ('Music', 'Music'), ('Health', 'Health'), ('Library', 'Library'), ('Misc.', 'Misc.')], default='Math', max_length=15)),
                ('work', models.CharField(error_messages={'required': 'Please enter what needs to be done'}, max_length=50, verbose_name='Assigned Work:')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
                'permissions': (('can_add_multi_classes', 'Can add to multiple classes'),),
            },
        ),
        migrations.CreateModel(
            name='Hwk_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('due_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.Kalendar')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass', verbose_name='Class')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
