# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        ('classlists', '0002_auto_20160805_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, choices=[('Language', 'Language'), ('Math', 'Math'), ('Science', 'Science'), ('French', 'French'), ('Visual Art', 'Visual Art'), ('Phys Ed.', 'Phys Ed.'), ('Geography', 'Geography'), ('History', 'History'), ('Drama', 'Drama'), ('Dance', 'Dance'), ('Media', 'Media'), ('Music', 'Music'), ('Health', 'Health'), ('Library', 'Library'), ('Misc', 'Misc.')], max_length=10, null=True)),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('klass', models.ManyToManyField(to='classlists.Klass')),
            ],
        ),
    ]
