# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classlists', '0002_auto_20160805_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_on', models.DateTimeField()),
                ('msg_text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass')),
                ('msg_replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msgs.Msg')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('last_msg', models.DateTimeField()),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homework.Homework')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass')),
            ],
        ),
        migrations.AddField(
            model_name='msg',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgs.Topic'),
        ),
    ]
