# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='classpage')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('klass', models.ManyToManyField(to='classlists.Klass', verbose_name='Class')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Class Message',
                'verbose_name_plural': 'Class Messages',
            },
        ),
    ]
